volumes:
    supera_enem_postgres_data: {}
    supera_enem_postgres_backup: {}

services:
  postgres:
    build:
        context: .
        dockerfile: ./compose/postgres/Dockerfile
    image: postgres
    volumes:
      - supera_enem_postgres_data:/var/lib/postgresql/data
      - supera_enem_postgres_backup:/backups
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./compose/spring/Dockerfile
    image: spring
    volumes:
      - .:/app
    env_file:
      - ./.envs/.spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    env_file:
      - ./.envs/.postgres
    environment:
      DATA_SOURCE_NAME: "postgresql://NSmoJtFZRGitRofNFrUxNyaqGbRRbMdA:3b7VMmu5pMwybV1ncbvI1SkT7Bur0Q7zhjDvoh7vRyZ5VgjK88c9ESuqmGZI7ZRM@postgres:5432/enem?sslmode=disable"
    links:
      - postgres
      - prometheus
