volumes:
  supera_enem_postgres_data: {}
  supera_enem_postgres_backup: {}
  keycloak_data: {}
  minio_data: {}
  minio_config: {}
services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: supera_enem_postgres:latest
    container_name: supera_enem_postgres
    volumes:
      - supera_enem_postgres_data:/var/lib/postgresql/data
      - supera_enem_postgres_backup:/backups
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

#  app:
#    build:
#      context: .
#      dockerfile: ./compose/spring/Dockerfile
#    image: supera_enem-app:latest
#    volumes:
#      - .:/app
#    environment:
#      - DOTENV_PATH=.envs/.spring
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/enem
#      - SPRING_DATASOURCE_USERNAME=NSmoJtFZRGitRofNFrUxNyaqGbRRbMdA
#      - SPRING_DATASOURCE_PASSWORD=3b7VMmu5pMwybV1ncbvI1SkT7Bur0Q7zhjDvoh7vRyZ5VgjK88c9ESuqmGZI7ZRM
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_SHOW_SQL=true
#      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
#      - SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS=true
#    env_file:
#      - ./.envs/.spring
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - minio

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    env_file:
      - ./.envs/.postgres
    environment:
      DATA_SOURCE_NAME: "postgresql://NSmoJtFZRGitRofNFrUxNyaqGbRRbMdA:3b7VMmu5pMwybV1ncbvI1SkT7Bur0Q7zhjDvoh7vRyZ5VgjK88c9ESuqmGZI7ZRM@postgres:5432/enem?sslmode=disable"
    links:
      - postgres
      - prometheus

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/enem
      - KC_DB_USERNAME=NSmoJtFZRGitRofNFrUxNyaqGbRRbMdA
      - KC_DB_PASSWORD=3b7VMmu5pMwybV1ncbvI1SkT7Bur0Q7zhjDvoh7vRyZ5VgjK88c9ESuqmGZI7ZRM
    command: start-dev
    ports:
      - "8081:8080"
    volumes:
      - ./scripts/init-keycloak.sql:/docker-entrypoint-initdb.d/init-keycloak.sql
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" #Interface
      - "9001:9001" #ADM
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
