volumes:
    supera_enem_postgres_data: {}
    supera_enem_postgres_backup: {}

services:
  postgres:
    build:
        context: .
        dockerfile: ./compose/postgres/Dockerfile
    image: postgres
    volumes:
      - supera_enem_postgres_data:/var/lib/postgresql/data
      - supera_enem_postgres_backup:/backups
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./compose/spring/Dockerfile
    image: spring
    volumes:
      - .:/app
    env_file:
      - ./.envs/.spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres