volumes:
    supera_enem_postgres_data: {}
    supera_enem_postgres_backup: {}

services:
  app:
    build:
      context: .
      dockerfile: ./compose/spring/Dockerfile
    image: supera_enem_spring:latest
    container_name: supera_enem_spring
    volumes:
      - .:/app
    environment:
      - DOTENV_PATH=.envs/.spring
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/enem
      - SPRING_DATASOURCE_USERNAME=NSmoJtFZRGitRofNFrUxNyaqGbRRbMdA
      - SPRING_DATASOURCE_PASSWORD=3b7VMmu5pMwybV1ncbvI1SkT7Bur0Q7zhjDvoh7vRyZ5VgjK88c9ESuqmGZI7ZRM
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS=true
    env_file:
      - ./.envs/.spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    build:
        context: .
        dockerfile: ./compose/postgres/Dockerfile
    image: supera_enem_postgres:latest
    container_name: supera_enem_postgres
    volumes:
      - supera_enem_postgres_data:/var/lib/postgresql/data
      - supera_enem_postgres_backup:/backups
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    env_file:
      - ./.envs/.postgres
    environment:
      DATA_SOURCE_NAME: "postgresql://NSmoJtFZRGitRofNFrUxNyaqGbRRbMdA:3b7VMmu5pMwybV1ncbvI1SkT7Bur0Q7zhjDvoh7vRyZ5VgjK88c9ESuqmGZI7ZRM@postgres:5432/enem?sslmode=disable"
    links:
      - postgres
      - prometheus