CREATE TABLE address
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    house_number VARCHAR(255)                            NOT NULL,
    street       VARCHAR(255)                            NOT NULL,
    neighborhood VARCHAR(255)                            NOT NULL,
    city         VARCHAR(255)                            NOT NULL,
    state        VARCHAR(255)                            NOT NULL,
    zip_code     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE answer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text        CHAR                                    NOT NULL,
    correct     BOOLEAN                                 NOT NULL,
    question_id BIGINT,
    test_id     BIGINT,
    CONSTRAINT pk_answer PRIMARY KEY (id)
);

CREATE TABLE content
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    content_weight  DOUBLE PRECISION                        NOT NULL,
    question_weight DOUBLE PRECISION                        NOT NULL,
    subject_id      BIGINT,
    CONSTRAINT pk_content PRIMARY KEY (id)
);

CREATE TABLE image
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url         VARCHAR(255),
    description VARCHAR(255),
    question_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE performance
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id       BIGINT                                  NOT NULL,
    content_id       BIGINT                                  NOT NULL,
    performance_rate DOUBLE PRECISION                        NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_performance PRIMARY KEY (id)
);

CREATE TABLE question
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text         VARCHAR(255),
    answer       CHAR                                    NOT NULL,
    answers_json TEXT,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

CREATE TABLE question_contents
(
    content_id  BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    CONSTRAINT pk_question_contents PRIMARY KEY (content_id, question_id)
);

CREATE TABLE student
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    keycloak_id  VARCHAR(255)                            NOT NULL,
    username     VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    dream_course VARCHAR(255)                            NOT NULL,
    phone        VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    birth_date   date                                    NOT NULL,
    address_id   BIGINT,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE student_subject
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id     BIGINT                                  NOT NULL,
    subject_id     BIGINT                                  NOT NULL,
    subject_weight DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_student_subject PRIMARY KEY (id)
);

CREATE TABLE subject
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_subject PRIMARY KEY (id)
);

CREATE TABLE test
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    date       date                                    NOT NULL,
    student_id BIGINT,
    CONSTRAINT pk_test PRIMARY KEY (id)
);

CREATE TABLE test_questions
(
    question_id BIGINT NOT NULL,
    test_id     BIGINT NOT NULL
);

CREATE TABLE weekly_report
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date                                    NOT NULL,
    student_id BIGINT,
    CONSTRAINT pk_weeklyreport PRIMARY KEY (id)
);

CREATE TABLE weekly_report_content
(
    content_id       BIGINT NOT NULL,
    weekly_report_id BIGINT NOT NULL,
    CONSTRAINT pk_weekly_report_content PRIMARY KEY (content_id, weekly_report_id)
);

ALTER TABLE student
    ADD CONSTRAINT uc_student_email UNIQUE (email);

ALTER TABLE student
    ADD CONSTRAINT uc_student_keycloak UNIQUE (keycloak_id);

ALTER TABLE student
    ADD CONSTRAINT uc_student_username UNIQUE (username);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_TEST FOREIGN KEY (test_id) REFERENCES test (id);

ALTER TABLE content
    ADD CONSTRAINT FK_CONTENT_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subject (id);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE performance
    ADD CONSTRAINT FK_PERFORMANCE_ON_CONTENT FOREIGN KEY (content_id) REFERENCES content (id);

ALTER TABLE performance
    ADD CONSTRAINT FK_PERFORMANCE_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE student_subject
    ADD CONSTRAINT FK_STUDENT_SUBJECT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE student_subject
    ADD CONSTRAINT FK_STUDENT_SUBJECT_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subject (id);

ALTER TABLE test
    ADD CONSTRAINT FK_TEST_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE weekly_report
    ADD CONSTRAINT FK_WEEKLYREPORT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE question_contents
    ADD CONSTRAINT fk_quecon_on_content FOREIGN KEY (content_id) REFERENCES content (id);

ALTER TABLE question_contents
    ADD CONSTRAINT fk_quecon_on_question FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE test_questions
    ADD CONSTRAINT fk_tesque_on_question FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE test_questions
    ADD CONSTRAINT fk_tesque_on_test_entity FOREIGN KEY (test_id) REFERENCES test (id);

ALTER TABLE weekly_report_content
    ADD CONSTRAINT fk_weerepcon_on_content FOREIGN KEY (content_id) REFERENCES content (id);

ALTER TABLE weekly_report_content
    ADD CONSTRAINT fk_weerepcon_on_weekly_report FOREIGN KEY (weekly_report_id) REFERENCES weekly_report (id);